import { tokens } from "./tokens";

export { tokens };

export const S = {
  wrap: {
    fontFamily: tokens.typography.fontFamily,
    minHeight: "100vh",
    width: "100%",
    background: tokens.colors.slate[50],
    color: tokens.colors.slate[900],
    display: "flex",
    position: "relative",
  },
  sidebar: {
    width: 260,
    background: "linear-gradient(180deg, #0B132B 0%, #111C44 100%)",
    color: tokens.colors.slate[50],
    display: "flex",
    flexDirection: "column",
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 100,
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: "4px 0 24px rgba(11, 19, 43, 0.4)",
    transition: "all 0.25s cubic-bezier(0.16, 1, 0.3, 1)",
  },
  sideLogo: {
    padding: "24px 20px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.07)",
  },
  sideNav: {
    flex: 1,
    padding: "16px 12px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  sideItem: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 16px",
    borderRadius: tokens.radii.lg,
    cursor: "pointer",
    fontSize: 13.5,
    fontWeight: active ? 600 : 500,
    background: active
      ? "linear-gradient(135deg, rgba(20, 184, 166, 0.2) 0%, rgba(2, 132, 199, 0.15) 100%)"
      : "transparent",
    color: active ? "#2DD4BF" : "rgba(241, 245, 249, 0.72)",
    border: active ? "1px solid rgba(45, 212, 191, 0.35)" : "1px solid transparent",
    boxShadow: active ? "0 2px 12px rgba(20, 184, 166, 0.18)" : "none",
    transition: tokens.transitions.default,
  }),
  main: {
    marginLeft: 260,
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: tokens.colors.slate[50],
    flex: 1,
    width: "calc(100% - 260px)",
    minWidth: 0,
    boxSizing: "border-box",
  },
  topbar: {
    background: tokens.colors.surface.topbar,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    borderBottom: `1px solid ${tokens.colors.slate[200]}`,
    padding: "14px 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 40,
    boxShadow: tokens.shadows.xs,
    width: "100%",
    boxSizing: "border-box",
  },
  content: {
    flex: 1,
    padding: "24px 32px",
    width: "100%",
    boxSizing: "border-box",
    minWidth: 0,
  },
  card: {
    background: tokens.colors.surface.card,
    borderRadius: tokens.radii.xl,
    border: `1px solid ${tokens.colors.slate[200]}`,
    padding: "24px 28px",
    marginBottom: 24,
    boxShadow: tokens.shadows.sm,
    transition: tokens.transitions.default,
  },
  btn: {
    padding: "9px 18px",
    borderRadius: tokens.radii.md,
    border: "none",
    fontWeight: 600,
    fontSize: 13.5,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    transition: tokens.transitions.fast,
    boxShadow: tokens.shadows.xs,
  },
  btnPrimary: {
    background: "linear-gradient(135deg, #0D9488 0%, #0284C7 100%)",
    color: "#FFFFFF",
    boxShadow: tokens.shadows.primaryGlow,
    border: "none",
  },
  btnSecondary: {
    background: "#FFFFFF",
    color: tokens.colors.slate[700],
    border: `1px solid ${tokens.colors.slate[300]}`,
    boxShadow: tokens.shadows.xs,
  },
  btnDanger: {
    background: tokens.colors.semantic.danger.bg,
    color: tokens.colors.semantic.danger.text,
    border: `1px solid ${tokens.colors.semantic.danger.border}`,
  },
  btnSuccess: {
    background: tokens.colors.semantic.success.bg,
    color: tokens.colors.semantic.success.text,
    border: `1px solid ${tokens.colors.semantic.success.border}`,
  },
  btnGhost: {
    background: "transparent",
    color: tokens.colors.slate[500],
    border: "1px solid transparent",
    boxShadow: "none",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: tokens.radii.md,
    border: `1px solid ${tokens.colors.slate[300]}`,
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: "#FFFFFF",
    color: tokens.colors.slate[900],
    transition: tokens.transitions.fast,
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: tokens.colors.slate[700],
    marginBottom: 6,
    display: "block",
  },
  badge: (color) => {
    const colorMap = {
      green: { bg: "#ECFDF5", text: "#065F46", border: "#A7F3D0" },
      blue: { bg: "#F0F9FF", text: "#075985", border: "#BAE6FD" },
      teal: { bg: "#F0FDFA", text: "#0F766E", border: "#99F6E4" },
      amber: { bg: "#FFFBEB", text: "#92400E", border: "#FDE68A" },
      red: { bg: "#FEF2F2", text: "#991B1B", border: "#FECACA" },
      purple: { bg: "#F5F3FF", text: "#5B21B6", border: "#DDD6FE" },
      indigo: { bg: "#EEF2FF", text: "#3730A3", border: "#C7D2FE" },
      cyan: { bg: "#ECFEFF", text: "#155E75", border: "#A5F3FC" },
      slate: { bg: "#F1F5F9", text: "#334155", border: "#E2E8F0" },
    };
    const style = colorMap[color] || colorMap.slate;
    return {
      padding: "4px 10px",
      borderRadius: tokens.radii.full,
      fontSize: 12,
      fontWeight: 600,
      background: style.bg,
      color: style.text,
      border: `1px solid ${style.border}`,
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
    };
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 20 },
  grid4: { display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 20 },
  statCard: {
    background: tokens.colors.surface.card,
    borderRadius: tokens.radii.xl,
    border: `1px solid ${tokens.colors.slate[200]}`,
    padding: "22px 24px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 14,
    boxShadow: tokens.shadows.sm,
    transition: tokens.transitions.default,
  },
  tableWrap: {
    overflowX: "auto",
    borderRadius: tokens.radii.lg,
    border: `1px solid ${tokens.colors.slate[200]}`,
    background: tokens.colors.surface.card,
    boxShadow: tokens.shadows.xs,
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 13.5 },
  th: {
    padding: "14px 18px",
    background: tokens.colors.slate[50],
    textAlign: "left",
    fontWeight: 600,
    fontSize: 12,
    color: tokens.colors.slate[500],
    borderBottom: `1px solid ${tokens.colors.slate[200]}`,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "14px 18px",
    borderBottom: `1px solid ${tokens.colors.slate[100]}`,
    color: tokens.colors.slate[700],
    fontSize: 13.5,
  },
  modal: {
    position: "fixed",
    inset: 0,
    width: "100vw",
    height: "100vh",
    background: "rgba(11, 19, 43, 0.72)",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    zIndex: 99999,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 16px",
    overflowY: "auto",
    boxSizing: "border-box",
  },
  modalBox: {
    background: "#FFFFFF",
    borderRadius: tokens.radii.xxl,
    width: "100%",
    maxWidth: 680,
    padding: 32,
    position: "relative",
    boxShadow: tokens.shadows.xl,
    border: `1px solid ${tokens.colors.slate[200]}`,
  },
  tag: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 12px",
    borderRadius: tokens.radii.full,
    fontSize: 12.5,
    fontWeight: 600,
    gap: 6,
  },
};
