export const S = {
  wrap: {
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, sans-serif",
    minHeight: "100vh",
    background: "#F8FAFC",
    color: "#0F172A",
  },
  sidebar: {
    width: 240,
    background: "linear-gradient(180deg, #064E3B 0%, #0F172A 100%)",
    color: "#F8FAFC",
    display: "flex",
    flexDirection: "column",
    position: "fixed",
    top: 0,
    left: 0,
    bottom: 0,
    zIndex: 100,
    borderRight: "1px solid rgba(255, 255, 255, 0.08)",
    boxShadow: "4px 0 24px rgba(6, 78, 59, 0.15)",
  },
  sideLogo: {
    padding: "24px 20px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
  },
  sideNav: {
    flex: 1,
    padding: "16px 12px",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  sideItem: (active) => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 16px",
    borderRadius: 10,
    cursor: "pointer",
    fontSize: 14,
    fontWeight: active ? 600 : 500,
    background: active
      ? "linear-gradient(135deg, rgba(16, 185, 129, 0.22) 0%, rgba(14, 165, 233, 0.22) 100%)"
      : "transparent",
    color: active ? "#34D399" : "rgba(240, 253, 244, 0.75)",
    borderLeft: active ? "3px solid #34D399" : "3px solid transparent",
    transition: "all 0.18s ease",
  }),
  main: {
    marginLeft: 240,
    minHeight: "100vh",
    display: "flex",
    flexDirection: "column",
    background: "#F8FAFC",
  },
  topbar: {
    background: "rgba(255, 255, 255, 0.9)",
    backdropFilter: "blur(12px)",
    borderBottom: "1px solid #E2E8F0",
    padding: "14px 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    position: "sticky",
    top: 0,
    zIndex: 50,
    boxShadow: "0 1px 3px 0 rgba(15, 23, 42, 0.03)",
  },
  content: {
    flex: 1,
    padding: "32px",
    maxWidth: 1400,
    margin: "0 auto",
    width: "100%",
  },
  card: {
    background: "#FFFFFF",
    borderRadius: 16,
    border: "1px solid #E2E8F0",
    padding: "24px 28px",
    marginBottom: 24,
    boxShadow: "0 1px 3px 0 rgba(15, 23, 42, 0.04)",
    transition: "all 0.2s ease",
  },
  btn: {
    padding: "9px 18px",
    borderRadius: 10,
    border: "none",
    fontWeight: 600,
    fontSize: 13,
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    transition: "all 0.18s ease",
    boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
  },
  btnPrimary: {
    background: "linear-gradient(135deg, #0D9488 0%, #0284C7 100%)",
    color: "#FFFFFF",
    boxShadow: "0 4px 12px rgba(13, 148, 136, 0.25)",
  },
  btnSecondary: {
    background: "#FFFFFF",
    color: "#334155",
    border: "1px solid #CBD5E1",
    boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.04)",
  },
  btnDanger: {
    background: "#FEF2F2",
    color: "#DC2626",
    border: "1px solid #FECACA",
  },
  btnSuccess: {
    background: "#ECFDF5",
    color: "#059669",
    border: "1px solid #A7F3D0",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid #CBD5E1",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    background: "#FFFFFF",
    color: "#0F172A",
    transition: "all 0.18s ease",
  },
  label: {
    fontSize: 13,
    fontWeight: 600,
    color: "#334155",
    marginBottom: 6,
    display: "block",
  },
  badge: (color) => {
    const colorMap = {
      green: { bg: "#ECFDF5", text: "#047857", border: "#A7F3D0" },
      blue: { bg: "#F0F9FF", text: "#0369A1", border: "#BAE6FD" },
      teal: { bg: "#F0FDF4", text: "#0D9488", border: "#99F6E4" },
      amber: { bg: "#FFFBEB", text: "#B45309", border: "#FDE68A" },
      red: { bg: "#FEF2F2", text: "#B91C1C", border: "#FECACA" },
      purple: { bg: "#F5F3FF", text: "#6D28D9", border: "#DDD6FE" },
      slate: { bg: "#F1F5F9", text: "#475569", border: "#E2E8F0" },
    };
    const style = colorMap[color] || colorMap.slate;
    return {
      padding: "4px 10px",
      borderRadius: 20,
      fontSize: 12,
      fontWeight: 600,
      background: style.bg,
      color: style.text,
      border: `1px solid ${style.border}`,
      display: "inline-flex",
      alignItems: "center",
      gap: 4,
    };
  },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 },
  grid3: { display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 20 },
  statCard: {
    background: "#FFFFFF",
    borderRadius: 16,
    border: "1px solid #E2E8F0",
    padding: "20px 24px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    gap: 12,
    boxShadow: "0 1px 3px 0 rgba(15, 23, 42, 0.04)",
    transition: "all 0.2s ease",
  },
  tableWrap: {
    overflowX: "auto",
    borderRadius: 12,
    border: "1px solid #E2E8F0",
    background: "#FFFFFF",
  },
  table: { width: "100%", borderCollapse: "collapse", fontSize: 14 },
  th: {
    padding: "14px 18px",
    background: "#F8FAFC",
    textAlign: "left",
    fontWeight: 600,
    fontSize: 12,
    color: "#64748B",
    borderBottom: "1px solid #E2E8F0",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    whiteSpace: "nowrap",
  },
  td: {
    padding: "14px 18px",
    borderBottom: "1px solid #F1F5F9",
    color: "#334155",
    fontSize: 14,
  },
  modal: {
    position: "fixed",
    inset: 0,
    background: "rgba(15, 23, 42, 0.6)",
    backdropFilter: "blur(6px)",
    zIndex: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 16px",
    overflowY: "auto",
  },
  modalBox: {
    background: "#FFFFFF",
    borderRadius: 20,
    width: "100%",
    maxWidth: 680,
    padding: 32,
    position: "relative",
    boxShadow: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
    border: "1px solid #E2E8F0",
  },
  tag: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 12px",
    borderRadius: 20,
    fontSize: 13,
    fontWeight: 500,
    gap: 6,
  },
};
